/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sample.app;

public class App {
	public String getGreeting(String msg) {
		Navigator nav = new Navigator(msg);
		return nav.navigate();
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting(args[0]));
	}
}
