/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sample.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appTest() {
        App app = new App();
        assertNotNull(app.getGreeting("Name=users&Where=field%20like%20%27%25%27"),
                "app should have returned an empty string");
    }
}
